workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini
    scripts:
      - name: build number
        script: |
          echo "project: $PROJECT_BUILD_NUMBER"
          echo "build: $BUILD_NUMBER"
    publishing:
      email:
         - marijan@todah.hr
