workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini
    scripts:
      - name: build number
        script: |
          echo $PROJECT_BUILD_NUMBER
    publishing:
      email:
         - marijan@todah.hr
